/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visualproc;
import com.mycompany.visualproc.Instructions;
import javax.swing.JOptionPane;

/**
 *
 * @author danil
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    VisualExecuter exec = BVisualExecuter.Build();
    public MainFrame() {
        initComponents();        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Regs = new javax.swing.JPanel();
        registersPanel1 = new com.mycompany.visualproc.RegistersPanel();
        Com = new javax.swing.JPanel();
        mostCommon1 = new com.mycompany.visualproc.MostCommon();
        Ins = new javax.swing.JPanel();
        all_Instructions1 = new com.mycompany.visualproc.All_Instructions();
        Inp = new javax.swing.JPanel();
        inputPanel1 = new com.mycompany.visualproc.InputPanel();
        Mem = new javax.swing.JPanel();
        memoryPanel1 = new com.mycompany.visualproc.MemoryPanel();
        Inp1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regs.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Regs.setLayout(new javax.swing.BoxLayout(Regs, javax.swing.BoxLayout.LINE_AXIS));
        Regs.add(registersPanel1);

        jPanel1.add(Regs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 250, 50));

        Com.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Com.setLayout(new javax.swing.BoxLayout(Com, javax.swing.BoxLayout.LINE_AXIS));
        Com.add(mostCommon1);

        jPanel1.add(Com, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 250, 130));

        Ins.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Ins.setLayout(new javax.swing.BoxLayout(Ins, javax.swing.BoxLayout.LINE_AXIS));
        Ins.add(all_Instructions1);

        jPanel1.add(Ins, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 380, 330));

        Inp.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Inp.setLayout(new javax.swing.BoxLayout(Inp, javax.swing.BoxLayout.LINE_AXIS));
        Inp.add(inputPanel1);

        jPanel1.add(Inp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 640, 70));

        Mem.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Mem.setLayout(new javax.swing.BoxLayout(Mem, javax.swing.BoxLayout.LINE_AXIS));
        Mem.add(memoryPanel1);

        jPanel1.add(Mem, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 250, 130));

        Inp1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Inp1.setLayout(new java.awt.GridLayout());

        jButton1.setText("Run next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Inp1.add(jButton1);

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Inp1.add(jButton2);

        jPanel1.add(Inp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 640, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            exec.doNext();
            Inp.setEnabled(false);
        } catch(Exception e) {}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Inp.setEnabled(true);
        try{exec.stop();} catch(Exception e) {}
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Com;
    private javax.swing.JPanel Inp;
    private javax.swing.JPanel Inp1;
    private javax.swing.JPanel Ins;
    private javax.swing.JPanel Mem;
    private javax.swing.JPanel Regs;
    private com.mycompany.visualproc.All_Instructions all_Instructions1;
    private com.mycompany.visualproc.InputPanel inputPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private com.mycompany.visualproc.MemoryPanel memoryPanel1;
    private com.mycompany.visualproc.MostCommon mostCommon1;
    private com.mycompany.visualproc.RegistersPanel registersPanel1;
    // End of variables declaration//GEN-END:variables
}
