/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.visualproc;

/**
 *
 * @author danil
 */
public class RegistersPanel extends javax.swing.JPanel implements IObserver{

    /**
     * Creates new form RegistersPanel
     */
    VisualExecuter exec;
    public RegistersPanel() {
        initComponents();
        exec = BVisualExecuter.Build();
        exec.addObs(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grid = new javax.swing.JPanel();
        R1 = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        R3 = new javax.swing.JLabel();
        R4 = new javax.swing.JLabel();
        R0v = new javax.swing.JLabel();
        R1v = new javax.swing.JLabel();
        R2v = new javax.swing.JLabel();
        R4v = new javax.swing.JLabel();

        Grid.setLayout(new java.awt.GridLayout(2, 4));

        R1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R1.setText("R0");
        Grid.add(R1);

        R2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R2.setText("R1");
        Grid.add(R2);

        R3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R3.setText("R2");
        Grid.add(R3);

        R4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R4.setText("R3");
        Grid.add(R4);

        R0v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R0v.setText("0");
        R0v.setAlignmentX(0.5F);
        R0v.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Grid.add(R0v);
        R0v.getAccessibleContext().setAccessibleName("0");

        R1v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R1v.setText("0");
        R1v.setAlignmentX(0.5F);
        R1v.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Grid.add(R1v);
        R1v.getAccessibleContext().setAccessibleName("0");

        R2v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R2v.setText("0");
        R2v.setAlignmentX(0.5F);
        R2v.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Grid.add(R2v);
        R2v.getAccessibleContext().setAccessibleName("0");

        R4v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R4v.setText("0");
        R4v.setAlignmentX(0.5F);
        R4v.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Grid.add(R4v);
        R4v.getAccessibleContext().setAccessibleName("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Grid, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Grid, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void event(VisualExecuter ve) throws Exception{
        R0v.setText(Integer.toString(ve.getRegister(0)));
        R1v.setText(Integer.toString(ve.getRegister(1)));
        R2v.setText(Integer.toString(ve.getRegister(2)));
        R4v.setText(Integer.toString(ve.getRegister(3)));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Grid;
    private javax.swing.JLabel R0v;
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R1v;
    private javax.swing.JLabel R2;
    private javax.swing.JLabel R2v;
    private javax.swing.JLabel R3;
    private javax.swing.JLabel R4;
    private javax.swing.JLabel R4v;
    // End of variables declaration//GEN-END:variables
}
